report:
  description: Run watchman report
  fields:
    create_file:
      example: true
      default: true
      required: false
      selector:
        boolean:
    send_notification:
      example: true
      default: false
      required: false
      selector:
        boolean:
    service:
      example: "notify.telegram"
      required: false
      selector:
        text:
    data:
      example: "parse_mode: html"

    parse_config:
      example: true
      default: false
      required: false
      selector:
        boolean:
    chunk_size:
      example: true
      default: false
      required: false
      selector:
        number:
          min: 0
          max: 100000
          mode: box

add_ignored_items:
  description: Add items (comma separated list) to ignored_items
  fields:
    items:
      required: true
      selector:
        text:

remove_ignored_items:
  description: Remove items (comma separated list) from ignored_items
  fields:
    items:
      required: true
      selector:
        text:

clear_ignored_items:
  description: Clear dynamic ignored items